language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: fVbHbn31eehL69/BBRNGW6Hj+PrjFCeBcC5GAGJ37g8RvgnZ2C/uaFzEwsi/Uagm2bJMsHxuRETPyf7yGOFCCvrgNtKddX/V7Nkn09sMop+rhReHOh00a/R8hChvVdXB3v1gKT9rgNPb+yPeiQ2+vac5hzZ/fM4CqJ9T7qnen5pebxkGKPSBIrLBe9q45FHhC/SOq8dxXwv5lEUNs6JmABimrkO+khPez8Leb8vxmbobxuSBXynX76wrNOmItLJxsIYQX0ywTOPQGtkzsWt6jmvWbjNWyfWs+YYOSSXUilLymhsvZ3ALz4bDRZ/8rOcFEFm7oraAbD7WWwqmts/igQBoQy3+iq1tdJ12o/d2fXNK8x6C0jFyY0XvDQ9Q4I0mAC+RKcj1YIOWl73XJhZO9uKBIS5WPruuctaBS4DGG9vjvuxm28J13d9m92JK25J9o/EH8QaOkaWX1efqQ+zEIif6YoKXtfgDJy1y3XN22aq/yXMvrwEbk7NvnKrqOWeTWZOGBSv68CXQyObsWa8v7FojhTtA8BJx+pGj2JA00idq04azHlRkAwaL7lAcXBSUsRlfMaoqAXv1/DR1NUlh2kym28vasyuRHNPCCMMaIBYp6quQRE2ofqEh6ElZwm4FMN9xSO5N4x0VYOw/xDn/LxJe4HO7q91zJaXDuBdtwpM=
  app: jonathanignacio-addressbook
  on:
    repo: jonathanignacio/addressbook
    branch: todo_tasks
